### ISSUE TITLE
DB: ERD and Remove unnecessary fields

### ISSUE THREAD

**Issue by lordYorden** [magshimim-next/cv-next#166]
- [x] Organizing database and removing unnecessary fields #118 
- [x] Creating an updated ERD

**Comment by lordYorden** [comment]
@Aradon267 Look at the new ERD, Is it okay to implement this?

**Comment by Aradon267** [comment]
Hmmm... Where is it?

**Comment by Aradon267** [comment]
Saw the changes, they were excellent! Several things to note and ask(mainly because I'm not sure about the signs like double circles I guess are an array?):
1. in CV, CategoryID is an array(as each CV can have up to 3 categories) same for workCategory in Profile.
2. In CV we don't need CategoryID and Category(as mentioned earlier)
3. is CommentOn something in the comments that references a profile and a CV?

**Comment by lordYorden** [comment]
The rhombuses represents relationships between entities and I suggest making a tri relation because a user comments on a CV hence tri, between profile, CV and comment

**Comment by lordYorden** [comment]
As for categories there is currently a major duplication because both work and CV has the exact same category system so I suggest separating it to a completely different entity for both. Using a new table, and making the table structure a lot more moduler and forward thinking.

**Comment by lordYorden** [comment]
I've added the Resulted Table Structure of the ERD also in the doc. @Aradon267

**Comment by Aradon267** [comment]
Ok this looks good and will ease the queries for sure!
2 things that I'm scared of here:
1. size limitations of the database (as we talked about) - the change adds a lot of tables and I'm afraid of hitting the limit
2. integrating this change we the code

**Comment by lordYorden** [comment]
As for space constraints, I will simulate the new db structure locally in order to understand the resources needed.
